from sympy import Eq, factor, solve, symbols

r, rf, rb, J, Jf, Jm, Jp = symbols('ρ, ρ_f, ρ_b, J, J_f, J_m, J_p')
E, P, D, B, M, H = symbols('E, P, D, B, M, H')
nabla, pt, e0, m0, lam, aL = symbols('∇, ∂_t, ε_0, µ_0, λ, α_L')
eq2 = Eq(nabla*E, r/e0)
eq3 = Eq(nabla*P, -rb)
eq4 = Eq(r, rf + rb)
eq5 = Eq(D, lam*(e0*E + P))
s = solve([eq2, eq3, eq4, eq5], [r, E, P, D])
print(f'∇·D = {nabla*s[D]}')
eq9 = Eq(nabla*B, (m0*J + m0*e0*pt*E)/aL)
eq10 = Eq(Jm, nabla*M/aL)
eq11 = Eq(J, Jf + Jm + Jp)
eq12 = Eq(Jp, pt*P)
eq13 = Eq(H, lam*(aL**2*B/m0 - M))
s = solve([eq5, eq9, eq10, eq11, eq12, eq13], [J, E, P, B, M, H])
print(f'∇×H = {factor(nabla*s[H])}')