from sympy import *

x, y, d = symbols('x, y, d')
numerator = (y**2 + (y-d)**2)*x**2 + 2*y**2*(y - d)**2
denominator = d**2*(2*y - d)**2*sqrt((x**2 + y**2)*(x**2 + (y - d)**2))
F = numerator / denominator
numerator, denominator = fraction(cancel(diff(F, x)))
print('F\' =')
print(factor(numerator))
print('-----------------')
print(factor(denominator))
print()
Foo = limit(F, x, +oo)
F0 = F.subs(x, 0)
print(f'F(0) = {F0}')
print()
F0 = 2*y**2*(y - d)**2/(d**2*y*(y - d)*(2*y - d)**2)
print('(-oo, 0], [d, +oo):')
numerator, denominator = fraction(cancel(Foo - F0))
print(f'F(+oo) - F(0) = {Foo} - {F0} = ')
print(factor(numerator))
print('-----------------')
print(factor(denominator))
print()
G1 = integrate(1/(2*y - d)**2, y)
print(f'G_1 = {G1}')
print()
print('[0, d]:')
numerator, denominator = fraction(cancel(Foo + F0))
print(f'F(+oo) - F(0) = {Foo} - {-F0} = ')
print(factor(numerator))
print('-----------------')
print(factor(denominator))
print()
G2 = integrate(1/d**2, y)
print(f'G_2 = {G2}')
print()
G1oo = limit(G1, y, +oo)
G1d = G1.subs(y, d)
G2d = G2.subs(y, d)
G20 = G2.subs(y, 0)
G10 = G1.subs(y, 0)
G1_oo = limit(G1, y, -oo)
print(f'G(+oo) - G(-oo) = [{G1oo} - {G1d}] + [{G2d} - {G20}] + [{G10} - {G1_oo}] = {G1oo - G1d + G2d - G20 + G10 - G1_oo}')