from sympy import Eq, factor, solve, symbols

r, rf, rb, J, Jf, Jm, Jp = symbols('ρ, ρ_f, ρ_b, J, J_f, J_m, J_p')
E, P, D, B, M, H = symbols('E, P, D, B, M, H')
nabla, pt, e0, m0, lam, aL = symbols('∇, ∂_t, ε_0, µ_0, λ, α_L')
eq1 = Eq(nabla*E, lam*r/e0)
eq2 = Eq(nabla*P, -rb)
eq3 = Eq(r, rf + rb)
eq4 = Eq(D, e0*E + lam*P)
s = solve([eq1, eq2, eq3, eq4], [r, E, P, D])
print(f'∇·D = {nabla*s[D]}')
eq6 = Eq(nabla*B, aL*m0*(lam*J + e0*pt*E))
eq7 = Eq(nabla*M, aL*Jm)
eq8 = Eq(J, Jf + Jm + Jp)
eq9 = Eq(Jp, pt*P)
eq10 = Eq(H, B/m0 - lam*M)
s = solve([eq4, eq6, eq7, eq8, eq9, eq10], [J, E, P, B, M, H])
print(f'∇×H = {factor(nabla*s[H])}')